### ISSUE TITLE
Periodic sync: A way to manually reset timers

### ISSUE THREAD

**Issue by jakearchibald** [WICG/BackgroundSync#164]
If the developer picks a minimum interval of 12 hours, this is an indication that they don't want to sync more frequently than every 12 hours.

However, what if the developer syncs manually, while the user is on their site? Should the developer be able to reset the interval counter?

```js
await swReg.periodicSync.resetInterval(tag);
```

cc @mugdhalakhani @beverloo

**Comment by mugdhalakhani** [comment]
Help me understand the motivation here better.

If the developer is able to cache content while servicing the periodicsync event, why would they need to sync again when the user visits the website?

The browser will ensure a gap of minInterval hours between periodicsync events and so the site can use these to prevent DDOSing themselves. Beyond that, the number of times the user visits the site isn't really in their control. They can choose to only sync if a reasonable amount of time has passed since the last sync, where the definition of reasonable is left to the developer.

**Comment by jakearchibald** [comment]
> If the developer is able to cache content while servicing the periodicsync event, why would they need to sync again when the user visits the website?

I thought you were recommending that here: https://github.com/WICG/BackgroundSync/issues/165#issuecomment-562131942?

`minInterval` allows developers to avoid using the user's battery more than they need to. There's no point updating every hour if they know the site only updates daily.

However, they may not get a sync as frequently as they'd like, due to lack-of-engagement penalties, so it seems like developers will often look for updates when the user visits the site.

If the developer has just performed a sync manually, shouldn't that reset timers as if it were a periodic sync?

**Comment by mugdhalakhani** [comment]
I see your point now :)
1. What if the browser automatically resets the timer when the user visits the site? That would solve this without requiring the developer to reset manually. Except -- the user might visit the site way too often and the developer might not want to reset the interval.
2. What if the developer re-registers periodic sync when the user visits the site _and_ they've just synced?

**Comment by jakearchibald** [comment]
We discussed this, and `minInterval` is only really to prevent DDOSing yourself, so I don't think the issue in the OP is important enough to worry about right now.
